eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8003/eureka/'
  instance:
    prefer-ip-address: true
server:
  port: 8004
spring:
  application:
    name: apigateway
  data:
    redis:
      host: redis-18690.c309.us-east-2-1.ec2.redns.redis-cloud.com
      port: 18690
      username: default
      password: ${REDIS_PASSWORD}
    
  cloud:
    gateway:
      routes:
        - id: userservice
          uri: 'lb://userservice'
          predicates:
            - 'Path=/user/**, /friend/**'
        - id: authservice
          uri: 'lb://authservice'
          predicates:
            - Path=/auth/**
        - id: postsservice
          uri: 'lb://postsservice'
          predicates:
            - 'Path=/post/**, /uploads/**, /like/**, /comment/**'
        - id: chatservice
          uri: 'lb://chatservice'
          predicates:
            - 'Path=/ws/**, /message/**'
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 
              - "http://localhost:4200"
              - "http://127.0.0.1:5500"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: '*'
            allowCredentials: true
      default-filters:
      - name: RequestRateLimiter
        args:
          key-resolver: "#{@ipKeyResolver}"
          redis-rate-limiter:
            replenishRate: 1
            burstCapacity: 5
management:
  endpoints:
    web:
      exposure:
        include:
        - health
        - info
  tracing:
    sampling:
      probability: 1.0
logging:
  file:
    name: /logs/apigateway/log.log