eureka:
  client:
    service-url:
      defaultZone: http://localhost:8003/eureka/
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: health,info
  tracing:
    sampling:
      probability: 1.0
server:
  port: 8001
  tomcat:
    max-swallow-size: 5MB
spring:
  application:
    name: postsservice
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://localhost:27017/Socio
  servlet:
    multipart:
      max-file-size: 300KB
logging:
  file:
    name: /logs/postsservice/log.log