eureka:
  client:
    service-url:
      defaultZone: http://localhost:8003/eureka/
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include:
        - health
        - info
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
server:
  port: 8000
  tomcat:
    max-swallow-size: 5MB
spring:
  application:
    name: userservice
  datasource:
    password: Hariya@123
    url: jdbc:mysql://localhost/socio
    username: meet
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
  servlet:
    multipart:
      max-file-size: 300KB
  cloud:
    openfeign:
      micrometer:
        enabled: true