eureka:
  client:
    service-url:
      defaultZone: http://localhost:8003/eureka/
  instance:
    prefer-ip-address: true
logging:
  file:
    name: /logs/authservice/log.log
management:
  endpoints:
    web:
      exposure:
        include: health,info
  tracing:
    sampling:
      probability: 1.0
server:
  port: 8002
spring:
  application:
    name: authservice
  datasource:
    password: Hariya@123
    url: jdbc:mysql://localhost/socio
    username: meet
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
